import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

// // import NextAuthProvider from './providers';
// // import './globals.css';

// export const metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

// export default function RootLayout({
// 	children,
// }: {
// 	children: React.ReactNode;
// }) {
// 	return (
// 		<html lang='en'>
// 			<body>
// 				{/* <NextAuthProvider>{children}</NextAuthProvider> */}
//         {children}
// 			</body>
// 		</html>
// 	);
// }
